name: workflow

on:
  push:
    branches:
      - main
  issues:
    types: [opened, reopened]

  schedule:
    - cron: "11 11 * * 5"
  
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "hello world" && echo "wtf"'
      
